@host = http://localhost:4444/api/photos

###
GET {{host}}

###
GET {{host}}/604fa99141a872789806f148

###
DELETE {{host}}/604fad13cacef0896d7af6d5

###
PUT {{host}}/604faea68da8ed9724c86082
Content-Type: application/json

{
	"title":"Vacaciones en acapulco",
	"description":"Con un vato todo ebrio"
}